AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  resize:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 1536
      Timeout: 10
      Role: 'arn:aws:iam::538422437880:role/lambda_s3_srmd_flyer_generator_role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /resize
            Method: ANY
      Environment:
        Variables:
          BUCKET: srmd-flyer-generator
          URL: 'http://srmd-flyer-generator.s3-website-us-east-1.amazonaws.com'
